# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nescient.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 512)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowTitle("Nescient")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/nessie.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.banner = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.banner.sizePolicy().hasHeightForWidth())
        self.banner.setSizePolicy(sizePolicy)
        self.banner.setMinimumSize(QtCore.QSize(0, 68))
        self.banner.setMaximumSize(QtCore.QSize(16777215, 68))
        self.banner.setText("")
        self.banner.setPixmap(QtGui.QPixmap(":/resources/banner.gif"))
        self.banner.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.banner.setObjectName("banner")
        self.verticalLayout.addWidget(self.banner)
        self.mainArea = QtWidgets.QWidget(self.centralwidget)
        self.mainArea.setObjectName("mainArea")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainArea)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftPane = QtWidgets.QWidget(self.mainArea)
        self.leftPane.setObjectName("leftPane")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.leftPane)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.treeWidget = QtWidgets.QTreeWidget(self.leftPane)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_4.addWidget(self.treeWidget)
        self.buttons = QtWidgets.QWidget(self.leftPane)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addButton = QtWidgets.QPushButton(self.buttons)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.addButton.setIcon(icon)
        self.addButton.setFlat(False)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_3.addWidget(self.addButton)
        self.removeButton = QtWidgets.QPushButton(self.buttons)
        icon = QtGui.QIcon.fromTheme("edit-delete")
        self.removeButton.setIcon(icon)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_3.addWidget(self.removeButton)
        self.exportButton = QtWidgets.QPushButton(self.buttons)
        self.exportButton.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.exportButton.setIcon(icon)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout_3.addWidget(self.exportButton)
        self.packButton = QtWidgets.QPushButton(self.buttons)
        icon = QtGui.QIcon.fromTheme("package-x-generic")
        self.packButton.setIcon(icon)
        self.packButton.setObjectName("packButton")
        self.horizontalLayout_3.addWidget(self.packButton)
        self.verticalLayout_4.addWidget(self.buttons)
        self.horizontalLayout_2.addWidget(self.leftPane)
        self.rightPane = QtWidgets.QWidget(self.mainArea)
        self.rightPane.setObjectName("rightPane")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightPane)
        self.verticalLayout_2.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.previewBox = QtWidgets.QGroupBox(self.rightPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.previewBox.sizePolicy().hasHeightForWidth())
        self.previewBox.setSizePolicy(sizePolicy)
        self.previewBox.setObjectName("previewBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.previewBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.filePreview = QtWidgets.QLabel(self.previewBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePreview.sizePolicy().hasHeightForWidth())
        self.filePreview.setSizePolicy(sizePolicy)
        self.filePreview.setText("")
        self.filePreview.setPixmap(QtGui.QPixmap(":/resources/nessie_lock.gif"))
        self.filePreview.setScaledContents(False)
        self.filePreview.setAlignment(QtCore.Qt.AlignCenter)
        self.filePreview.setObjectName("filePreview")
        self.verticalLayout_3.addWidget(self.filePreview)
        self.filePreviewName = QtWidgets.QLabel(self.previewBox)
        self.filePreviewName.setText("")
        self.filePreviewName.setAlignment(QtCore.Qt.AlignCenter)
        self.filePreviewName.setObjectName("filePreviewName")
        self.verticalLayout_3.addWidget(self.filePreviewName)
        self.verticalLayout_2.addWidget(self.previewBox)
        self.propertyBox = QtWidgets.QGroupBox(self.rightPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertyBox.sizePolicy().hasHeightForWidth())
        self.propertyBox.setSizePolicy(sizePolicy)
        self.propertyBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.propertyBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.propertyBox.setFlat(False)
        self.propertyBox.setCheckable(False)
        self.propertyBox.setObjectName("propertyBox")
        self.formLayout = QtWidgets.QFormLayout(self.propertyBox)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.propertyBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.packingMode = QtWidgets.QLabel(self.propertyBox)
        self.packingMode.setText("N/A")
        self.packingMode.setObjectName("packingMode")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.packingMode)
        self.label_3 = QtWidgets.QLabel(self.propertyBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.fileSize = QtWidgets.QLabel(self.propertyBox)
        self.fileSize.setText("0 MiB")
        self.fileSize.setOpenExternalLinks(False)
        self.fileSize.setObjectName("fileSize")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fileSize)
        self.label_7 = QtWidgets.QLabel(self.propertyBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.fileType = QtWidgets.QLabel(self.propertyBox)
        self.fileType.setText("N/A")
        self.fileType.setObjectName("fileType")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fileType)
        self.label_2 = QtWidgets.QLabel(self.propertyBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fileName = QtWidgets.QLabel(self.propertyBox)
        self.fileName.setObjectName("fileName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileName)
        self.verticalLayout_2.addWidget(self.propertyBox)
        self.horizontalLayout_2.addWidget(self.rightPane)
        self.verticalLayout.addWidget(self.mainArea)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setFormat("%p%")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 29))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Options = QtWidgets.QMenu(self.menubar)
        self.menu_Options.setObjectName("menu_Options")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.actionOpen)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Options.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "File"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.removeButton.setText(_translate("MainWindow", "Remove"))
        self.exportButton.setText(_translate("MainWindow", "Export"))
        self.packButton.setText(_translate("MainWindow", "Pack"))
        self.previewBox.setTitle(_translate("MainWindow", "Preview"))
        self.propertyBox.setTitle(_translate("MainWindow", "Archive Properties"))
        self.label.setText(_translate("MainWindow", "Packing mode:"))
        self.label_3.setText(_translate("MainWindow", "Size:"))
        self.label_7.setText(_translate("MainWindow", "Type:"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.fileName.setText(_translate("MainWindow", "N/A"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Options.setTitle(_translate("MainWindow", "Optio&ns"))
        self.menu_About.setTitle(_translate("MainWindow", "Abo&ut"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionNew.setText(_translate("MainWindow", "New"))

import resource_rc
